### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by mycrazycc** [ViRT1ST/BeDownloader#1]
It doesn't seem to work, it only shows downloading in progress 1/33 and nothing happens, it can correctly parse how many images are in the current project

**Comment by ViRT1ST** [comment]
Hi, send me link to project, i will check.

**Comment by mycrazycc** [comment]
<img width="490" alt="image" src="https://github.com/ViRT1ST/BeDownloader/assets/51710171/ca57a42d-862e-4f92-a29a-8760d2627b20">
Like this, no link can be downloaded My OS is Windows 11 22H2

**Comment by ViRT1ST** [comment]
Checked both of your URLs in a clean Windows 11 22H2 with all latest updates.
Everything works fine with the latest version of BeDownloader (1.0.9).

Try download latest version (1.0.9), then completely delete ".bedownloader" folder (C:\Users\C\.bedownloader) before running app. If it still doesn't work, change the download path (for example, to "C:\Downloads").

![Screenshot_3](https://github.com/ViRT1ST/BeDownloader/assets/45234752/7e5d1067-e692-4665-a2fa-ee4ef77dab30)
