### ISSUE TITLE
26 / 177

### ISSUE THREAD

**Issue by CATyPH** [ViRT1ST/BeDownloader#2]
Hi! Download 26 photo's only, but was 177 galleries with more than 26 photo's :)
for example: https://www.behance.net/art_of_ck
can you fix it?
thx!

os: win10

p.s. some problems with download history. I put new links, but receive such error:
![clipboard2](https://github.com/ViRT1ST/BeDownloader/assets/57801960/e28eec93-3c1d-408b-ac55-e013abc3d90e)

**Comment by ViRT1ST** [comment]
Hi, there was a problem with downloading projects marked as 18+. To view such projects Behance require user auth. I made temporary fix with fake behance account that I hardcoded in code to bypass this problem. Later I will update this part with more robust solution. For now, you can download new version (1.2.0) with temporary this fix.

Second problem with (all skipped by download history) -  just open "C:\Users\Admin\.bedownloader\settings.ini" file and change "false" in option "skipProjectsByHistory" to "true".

**Comment by CATyPH** [comment]
thanks for fix! it's all working now!
only file with setting was config.ini :)
